### ISSUE TITLE
Solicitud RP

### ISSUE THREAD

**Issue by fabianLeon** [udistrital/administrativa_cliente#2]

**Comment by fabianLeon** [comment]
1. En selección de cdp traer el Ordenador y el Estado del CDP, No se está mostrando.
2. Agregar la descripción de un Compromiso.
3. Modalidad seleción.
4. Label en Compromiso id -> Número.
5. Para los label dinámicos input y textarea según el caso.
6. Filtro adicional para fuentes de apropiación de acuerdo al tipo de rubro.
7. Agregar fabrica para evitar el envío de datos por $routeprovider.

**Comment by docg92** [comment]
8- Mostrar el numero de solicitud en la alerta
