### ISSUE TITLE
Estudio , analisis del estado actual de resoluciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/administrativa_cliente#298]
En la sección de resoluciones se manejara la segmentación de los rubros para el contrato ya que actualmente solo esta en valor sin segmentación.

Adicionalmente a esto el cliente de resoluciones y cumplidos deben integrarse, mas específicamente resoluciones se integra a cumplidos.

por ello en primera instancia se ha de proceder a un análisis y estudio del estado actual de este cliente.

La rama en la cual esta el cliente de resoluciones en en la rama `resoluciones`

**Comment by BrayanB24** [comment]
Se inicia el estudio del módulo de resoluciones,  es necesario requerir el permiso de WSO2 con los roles respectivos para ingresar en la aplicación.

**Comment by BrayanB24** [comment]
En la rama resoluciones se encuentra el desarrollo realizado para este módulo. Es necesario primero realizar la instalación de dependencias de la rama máster y luego cambiarse a la rama resoluciones para que el cliente funcione de manera correcta. Es necesario hacer la navegación por el cliente con las rutas que serán especificadas en el documento de informe.
