### ISSUE TITLE
Confirmar fechas al registrar elementos de catalogo

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/administrativa_cliente#497]
Posible ajuste a la HU:

https://docs.google.com/spreadsheets/d/1qFq94mre8YPF66ZXWnNsOH_O2n2FoPcF/edit#gid=2105797956

![image](https://user-images.githubusercontent.com/6588872/124019770-12a15800-d9af-11eb-8db4-ef8a3f15e45b.png)

**Comment by mcrubianot** [comment]
Se envía el siguiente correo con el fin de que la respuesta sea enviada por escrito por parte de la Sección de Almacén e Inventarios:



Buenas tardes, de conformidad con las validaciones que se han venido realizando con respecto a las funcionalidades de Arka II en el entorno de pruebas, comedidamente nos permitimos solicitar su colaboración en el sentido de confirmarnos si las fechas de Inicio y fecha de finalización se requieran puntualmente para la creación de un elemento dentro del catálogo de bienes o si por el contrario son datos que no se deben dejar en los desarrollos.

Se anexa la imagen de cómo se encuentran actualmente definidos estos registros

 
image.png

Quedamos atentos a sus comentarios.

**Comment by mcrubianot** [comment]
En reunión de aprobación de historias de usuario de Catálogo de bienes y Actas de recibido, quedó la observación que la fecha final no va.  Observación marcada en color rojo en la Historia de Usuario correspondiente.
