### ISSUE TITLE
Confirmar porcentajes IVA

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/administrativa_cliente#498]
Porcentajes a ser usados en Carga de Elementos (Arka II)

![image](https://user-images.githubusercontent.com/6588872/124026564-762f8380-d9b7-11eb-97ce-47c098841d14.png)

**Comment by mcrubianot** [comment]
Tarifa general del Iva
La tarifa general del Iva es del 19 según lo contempla el artículo 468 del estatuto tributario modificado por la ley 1819 de 2016.

Tarifa del 5%
El artículo 468-1 del estatuto tributario contempla un listado productos que están gravados con la tarifa del 5%.

Bienes exentos del impuesto a las ventas
Los bienes exentos están gravados con una tarifa de 0%, lo que derecho al responsable a descontar el Iva que haya pagado al momento de adquirir dichos productos.

Bienes Excluidos
Los bienes excluidos son aquellos que por expresa disposición legal no están gravados con el impuesto.
