### ISSUE TITLE
Reunión definición mesas de trabajo para Arka II

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/administrativa_cliente#514]
Se cita por parte del Gerente a reunión para definir como se realizarán las mesas de trabajo para Arka II

Se deja el link de la reunión 

https://drive.google.com/file/d/1Fq7i7X51Qxs-1bUSJNTB6KJA6F5CA1E9/view

**Comment by AlexFBP** [comment]
Duplicado de #562, dado que se cerró allá, se cierra acá del mismo modo
