### ISSUE TITLE
Observaciones para el tema de "Ajustes" en Arka II

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/administrativa_cliente#529]
Se revisa el desarrollo actual que se encuentra en el entorno de prubas de Arka II y se dejan las siguientes observaciones para analizar con el Líder Técnico y desarrollador a cargo

- [x] El sistema automáticamente sabe como identificar las cuentas que se deberán utilizar?
- [ ] Tener en cuenta que cuando se cierra el mes contable, no se pueden hacer ajustes sino posteriormente a dicha fecha de cierre, es decir no se puede modificar nada una vez un mes esté cerrado
- [ ] Cómo se manejaría el cierre del mes
- [x] Cómo se haría un ajuste que no se refiera a una anulación, sino a un cambio de bien (como lo ha planteado la Jefe de Almacén) y ese cambio no afecta ni cuentas ni valores
- [x] Que pasa al momento en que se surtió todo un proceso (acta de recibido, entrada, salida, bajas)  y la dependencia se dió cuenta de que el tercero se fue mal
- [x] O que pasaría si el tercero de la salida fue mal
- [x] Generar un consecutivo de ajustes, pues no se está mostrando ni alertando al respeto
- [x] Cómo consulto en la gestión de ajustes la acta, entrada, salida, baja, sobre la cual debo hacer el ajuste. Considero que hace falta una consulta de documentos

Si bien es cierto todo es una secuencia y todo debe estar bien pues el sistema está arrastrando información, no está demás revisar las opciones aquí plasmadas.

**Comment by mcrubianot** [comment]
No se ha realizado ninguna reunión con los ingenieros para hablar sobre el tema. Estoy al pendiente

@AlexFBP

**Comment by AlexFBP** [comment]
La mayoría ya quedó contemplado en el desarrollo del ajuste automático. Lo relacionado a cierres será tratado en su respectivo desarrollo, udistrital/arka_cliente#887
