### ISSUE TITLE
Reunión Revisión mockups Traslados con Desarrollador

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/administrativa_cliente#535]
Se realiza la respectiva mesa de trabajo

https://drive.google.com/file/d/1D1_sc4GzH19aQAaAG6zCbYjy_oDMM9Dl/view?usp=sharing

Y se levanta la siguiente acta 

https://docs.google.com/document/d/1b9y_6UCQGSCT8PCMu0uDHJX7UdlZswKbWVhj88LaeaY/edit

**Comment by mcrubianot** [comment]
Luego de la esa de trabajo no se ha revisado ningún tipo de información

**Comment by AlexFBP** [comment]
Mencionado en las referencias/consideraciones de udistrital/arka_cliente#926 , se podría cerrar este Issue @mcrubianot
